/*******************************************************************************
 * Copyright 2013 Sprachliche Informationsverarbeitung, University of Cologne
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package de.uni_koeln.spinfo.maalr.common.shared;

import de.uni_koeln.spinfo.maalr.common.server.IOverlayGenerator;

/**
 * Thrown if an error occurs when word forms are generated by
 * an instance of {@link IOverlayGenerator}. The message provided
 * by {@link GenerationFailedException#getMessage()} will be
 * shown to the user.
 * 
 * @author sschwieb
 *
 */
public class GenerationFailedException extends Exception {
	
	private static final long serialVersionUID = -7633975068143469253L;
	
	public GenerationFailedException() {}

	public GenerationFailedException(String message) {
		super(message);
	}

}
